version: "3.2"

services:
  app:
    image: devallday/nozama:0.2.0
    ports:
      - 8080:8080
  ci:
    image: jenkinsci/blueocean:1.9.0
    ports:
      - 8888:8080
    volumes:
      - type: volume
        source: jenkins-dev
        target: /var/jenkins_home
volumes:
  jenkins-dev:
