version: "3.2"

services:
  appwebservice:
    image: maven:3.6-jdk-8-alpine
    ports:
      - 8080:8080
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_PORT
    volumes:
      - type: bind
        source: "$PWD"
        target: /usr/src/app
      - type: bind
        source: "$HOME/.m2"
        target: "/root/.m2"
      - type: bind
        source: "$PWD/target"
        target: "/usr/src/app/target"
    working_dir: /usr/src/app
    depends_on:
      - postgres
    command: ["mvn", "spring-boot:run"]
  postgres:
    image: postgres:9.6
    ports:
      - 5432
    environment:
      - POSTGRES_DB
      - POSTGRES_PASSWORD
  simulator:
    image: java:8
    ports:
      - 4567:4567
    environment: 
      - NOZAMA_URL
      - NOZAMA_URL_DOCKER
    volumes:
      - type: bind
        source: "../simulation/simulator/"
        target: /usr/src/app
      - type: bind
        source: "$HOME/.m2"
        target: "/root/.m2"
      - type: bind
        source: "../simulation/simulator/target"
        target: "/usr/src/app/target"
    working_dir: /usr/src/app
    command: ["java", "-jar", "target/simulator-jar-with-dependencies.jar"]
