version: "3.2"

services:
  appwebservice:
    image: maven:3.6-jdk-8
    ports:
      - 8080:8080
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_PORT
    volumes:
      - type: bind
        source: "$PWD"
        target: /usr/src/app
      - type: bind
        source: "$HOME/.m2"
        target: "/root/.m2"
      - type: bind
        source: "$PWD/target"
        target: "/usr/src/app/target"
    working_dir: /usr/src/app
    depends_on:
      - postgres
    command: ["mvn", "spring-boot:run"]
  postgres:
    image: postgres:9.6
    ports:
      - 5432
    environment:
      - POSTGRES_DB
      - POSTGRES_PASSWORD
  sonarqube-server:
    image: sonarqube:7.4-community
    ports:
      - 9000:9000
    volumes:
      - type: bind
        source: "./sonarqube/conf"
        target: "/opt/sonarqube/conf"
      - type: bind
        souce: "./sonarqube/data"
        target: "/opt/sonarqube/data"
      - type: bind
        source: "./sonarqube/logs"
        target: "/opt/sonarqube/logs"