version: "3.2"

services:
  appwebservice:
    image: devallday/nozama:latest
    ports:
      - 8080:8080
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_PORT
    depends_on:
      - postgres
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_DB
      - POSTGRES_PASSWORD
    ports:
      - 5432
  simulator:
    image: devallday/simulator:latest
    environment:
      - NOZAMA_URL
      - NOZAMA_URL_DOCKER
    ports:
      - 4567:4567
