pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh '${PWD}/app'
                sh 'mvn -B -DskipTests clean install'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Generate documentation') {
            steps {
                sh 'mvn doxygen:generate'
            }
        }
        stage('Build image and Deliver') {
            steps {
                sh 'mvn dockerfile:build'
            }
        }
    }
}
