version: "3.2"

services:
  jenkins:
    image: jenkinsci/blueocean:1.9.0
    restart: unless-stopped
    ports:
      - 80:8080
    volumes:
      - type: volume
        source: jenkins-prod
        target: "/var/jenkins_home"
volumes:
  jenkins-prod:
