DROP DATABASE IF EXISTS nozama;
CREATE DATABASE nozama;
USE nozama;

CREATE TABLE client (
 clientID     INT UNSIGNED,
 name         VARCHAR(20) NOT NULL,
 db     VARCHAR(20)
);

CREATE TABLE user (
 userID       INT UNSIGNED,
 nameUser     VARCHAR(20) NOT NULL,
 username     VARCHAR(20) NOT NULL,
 password     VARCHAR(30) NOT NULL,
 clientID     INT UNSIGNED,
 rolID        INT UNSIGNED
);

CREATE TABLE rol (
 rolID        INT UNSIGNED,
 nameRol      VARCHAR(20) NOT NULL
);

ALTER TABLE client
ADD CONSTRAINT CLIENT_PK PRIMARY KEY (clientID);

ALTER TABLE rol
ADD CONSTRAINT ROL_PK PRIMARY KEY (rolID);

ALTER TABLE user
ADD CONSTRAINT USER_PK PRIMARY KEY (userID),
ADD CONSTRAINT USER_CLIENT_FK FOREIGN KEY (clientID) REFERENCES client (clientID),
ADD CONSTRAINT USER_ROL_FK FOREIGN KEY (rolID) REFERENCES rol (rolID);
